### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by w4nd3rhod3n**

### CODE REVIEW

**Comment by Darin755** [comment]
Can you clarify why this is necessary?

**Comment by Darin755** [comment]
I am closing this as I am unsure of its purpose

**Review by w4nd3rhod3n — COMMENTED** [review]
.devcontainer/devcontainer.json

**Comment by Darin755** [comment]
Yeah that still doesn't help me. You are going to need to justify why you created this file. I assume it is for some automated system but I don't know anything more than that.

**Pull request closed without merging**
